apiVersion: v1
kind: ReplicationController
metadata:
  name: registry
  namespace: default
  labels:
    k8s-app: registry
    version: "2.1"
spec:
  replicas: 1
  selector:
    k8s-app: registry
    version: "2.1"
  template:
    metadata:
      labels:
        k8s-app: registry
        version: "2.1"
    spec:
      containers:
      - name: registry
        image: registry.docker:5000/yeepay/registry:2.1
        resources:
          # keep request = limit to keep this container in guaranteed class
          limits:
            cpu: 4
            memory: 10Gi
          requests:
            cpu: 4
            memory: 10Gi
        volumeMounts:
        - name: registry
          mountPath: /var/lib/registry
        ports:
        - containerPort: 5000
          name: registry
          protocol: TCP
      volumes:
      - name: registry
        rbd: 
          monitors:
            - "10.149.149.2:6789"
            - "10.149.149.3:6789"
            - "10.149.149.4:6789"
          pool: rbd
          image: registry
          secretRef:
            name: ceph-secret
          fsType: ext4
          readOnly: false
