apiVersion: v1
kind: Service
metadata:
  name: registry
  namespace: default
  labels:
    k8s-app: registry
spec:
  selector:
    k8s-app: registry
  ports:
  - name: registry
    port: 5000
    targetPort: 5000
    protocol: TCP
    nodePort: 32500
  type: NodePort
