#! /bin/bash
#docker run -d -p 5000:5000 --restart=always --name registry  -v `pwd`/certs:/certs -v /etc/docker/registry/config.yaml:/etc/docker/registry/config.yaml -e REGISTRY_HTTP_TLS_CERTIFICATE=/certs/domain.crt  -e REGISTRY_HTTP_TLS_KEY=/certs/domain.key -v /images/:/var/lib/registry -e REGISTRY_STORAGE_DELETE_ENABLED=true  registry:2.1

#This is the normal way.
docker run -d -p 5000:5000 --restart=always --name registry  -v `pwd`/certs:/certs -e REGISTRY_HTTP_TLS_CERTIFICATE=/certs/domain.crt  -e REGISTRY_HTTP_TLS_KEY=/certs/domain.key -e REGISTRY_STORAGE_DELETE_ENABLED=true -v /images/:/var/lib/registry  registry:2.1

#docker run -d -p 5000:5000 --restart=always --name registry  -v `pwd`/certs:/certs -e REGISTRY_HTTP_TLS_CERTIFICATE=/certs/domain.crt  -e REGISTRY_HTTP_TLS_KEY=/certs/domain.key -e REGISTRY_STORAGE_DELETE_ENABLED:true -v /images/:/var/lib/registry  registry:2.1

#docker run -d -p 5000:5000 --restart=always --name registry  -v `pwd`/certs:/certs -e REGISTRY_HTTP_TLS_CERTIFICATE=/certs/domain.crt  -e REGISTRY_HTTP_TLS_KEY=/certs/domain.key -v /images/:/var/lib/registry -e REGISTRY_STORAGE_DELETE_ENABLED=true  registry:2.1
#docker run -d -p 5000:5000 --restart=always --name registry -v `pwd`/certs:/certs -v /etc/docker/registry/config.yml:/etc/docker/registry/config.yml -v /images/:/var/lib/registry registry:2.1 

#docker run -d -p 5000:5000 --restart=always --name registry -v /etc/docker/registry/config.yml:/etc/docker/registry/config.yml -v /images/:/var/lib/registry registry:2.1 
#docker run -d -p 5000:5000 --restart=always --name registry -v `pwd`/config.yml:/etc/docker/registry/config.yml -e DOCKER_REGISTRY_CONFIG=`pwd`/config.yml -e REGISTRY_STORAGE_DELETE_ENABLED=true -v /images/:/var/lib/registry registry:2.1
