apiVersion: v1
kind: ReplicationController
metadata:
  name: redis-master
  labels:
    name: redis-master
spec:
  replicas: 1
  selector:
    name: redis-master
  template:
    metadata:
      labels:
        name: redis-master
    spec:
      containers:
      - name: master-memory
        image: registry.test.com:5000/redis
        ports:
        - containerPort: 6379
        resources:
          limits:
            memory: "4096M"
