apiVersion: v1
kind: ReplicationController
metadata:
  name: redis-master
  namespace: offlinepos
  labels:
    name: redis-master
spec:
  replicas: 1
  selector:
    name: redis-master
  template:
    metadata:
      labels:
        name: redis-master
    spec:
      containers:
      - name: master-memory
        image: registry.docker:5000/redis
        env:
        - name: MASTERAUTH
          value: yeepayredis
        ports:
        - containerPort: 6379
        resources:
          limits:
            memory: "8092M"
