apiVersion: v1
kind: Service
metadata:
  name: redis-master
  namespace: offlinepos
  labels:
    name: redis-master
spec:
  type: NodePort
  ports:
  - port: 6379
    targetPort: 6379
    nodePort: 32379
  selector:
    name: redis-master
