apiVersion: v1
kind: Service
metadata:
  name: redis-slave
  namespace: offlinepos
  labels:
    name: redis-slave
spec:
  type: NodePort
  ports:
  - port: 6379
    targetPort: 6379
    nodePort: 32380
  selector:
    name: redis-slave
