apiVersion: v1
kind: Service
metadata:
  name: memcached
  labels:
    name: memcached
spec:
  type: NodePort
  ports:
  - port: 11211
    targetPort: 11211
    nodePort: 32211
    protocol: TCP
  selector:
    role: memcached
    mode: standalone
